//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShelterRusakov.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal
    {
        public int id { get; set; }
        public System.DateTime datestart { get; set; }
        public int idviewanimal { get; set; }
        public string name { get; set; }
        public bool pasport { get; set; }
        public int age { get; set; }
        public string service { get; set; }
        public System.DateTime dateend { get; set; }
    
        public virtual viewanimal viewanimal { get; set; }
    }
}
