//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShelterRusakov.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShelterRusakovEntities : DbContext
    {
        public ShelterRusakovEntities()
            : base("name=ShelterRusakovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<journal> journal { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<viewanimal> viewanimal { get; set; }
    }
}
