//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShelterRusakov.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewanimal
    {
        public viewanimal()
        {
            this.journal = new HashSet<journal>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<journal> journal { get; set; }
    }
}
